### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by parthms** [readmeio/rdme#1]
Everytime I try to upload my swagger.json file using either

`rdme swagger.json --token=xxxxxxxxxxxx`

or 

`oas host`

my JS heap runs out of memory. The swagger.json file is barely 52 kB. Not sure why the heap keeps running out of memory.

**Comment by domharrington** [comment]
Hey @parthms, did you ever get this resolved? Sorry for not responding quicker, this isn't really a monitored support channel. Please reopen if this is still a problem

**Comment by parthms** [comment]
I found an alternative solution. Thanks for reaching out.

**Comment by prowave** [comment]
@parthms What was the alternative solution?  Thanks.

**Comment by domharrington** [comment]
If you can provide a link to your swagger file it may help me to debug it. Can you reproduce it reliably? What OS? Thanks.
