### ISSUE TITLE
The version you specified (2.0) doesn't match any of the existing versions (2.0) in ReadMe.

### ISSUE THREAD

**Issue by Ebeid** [readmeio/rdme#1013]
I'm running the following command
`rdme openapi ./publish/$$$.json --key=rdme_$$$ --id=$$$`
on my swagger file I have the following 
`"info": {
        "version": "2.0"
    },`
My readme project already have version 2.0. I still get the following error
```
The version you specified (2.0) doesn't match any of the existing versions (2.0) in ReadMe.

https://docs.readme.com/main/reference and include the following link to your API log: 'https://docs.readme.com/main/logs/a8ff7561-a568-4efe-b4a6-486555ab632b'.
```
add to that when I try to access the url in the error message, I get the following error 

![image](https://github.com/readmeio/rdme/assets/8538238/99ae0d57-310f-4587-a084-8b8a410a6d00)

**Comment by kanadgupta** [comment]
Hi @Ebeid! Can you get in touch with us at support@readme.io? This is related to our API and we'll need more information about your project and the `id` parameter you're sending, so chatting privately will allow us to be more helpful. Thanks!

**Comment by Ebeid** [comment]
Then keep it open @kanadgupta until it is actually resolved.

**Comment by kanadgupta** [comment]
@Ebeid apologies for the abrupt closure! I did so because the actual issue is unrelated to `rdme` itself. Unfortunately we're a bit short-staffed due to the upcoming U.S. holiday weekend but our support team internally tracks the emails they receive so somebody will get back to you soon. Appreciate your patience!
