### ISSUE TITLE
GET /api-registry does not have any authentication

### ISSUE THREAD

**Issue by akil-rails** [readmeio/rdme#1021]
The GET /api-registry works without any auth [reference doc](https://docs.readme.com/main/reference/getapiregistry).

This means that anyone can access our api specification (if they obtain the registry-UUID in some way) . The api-registry should require access to the project like other APIs.

**Comment by erunion** [comment]
Hi! We're aware of this and this was an intentional decision to allow people to use [api](https://npm.im/api) to create on-the-fly SDKs.
