### ISSUE TITLE
Invalid JSON in Markdown upload response

### ISSUE THREAD

**Issue by eddspencer** [readmeio/rdme#108]
I am uploading Markdown documents with:
```
rdme docs . --version="v1.0" --key=[key]
```
using versoin 3.5.0.

They get uploaded successfully and in the response a get a JSON-like object with information on the upload. I am using Python to parse this response, but since it is not valid JSON this is not so simple, to be a valid JSON structure it needs to have double quotes on the keys: [docs](https://tools.ietf.org/html/rfc7159)

> An object structure is represented as a pair of curly brackets
   surrounding zero or more name/value pairs (or members).  **A name is a
   string**.  A single colon comes after each name, separating the name
   from the value.

Could this please be updated so that the response object has quoted key names?

Response object (with my data removed):

```
[ { __v: 0,
    version: '[version-id]',
    updatedAt: '2019-12-09T10:45:01.875Z',
    createdAt: '2019-12-09T10:45:01.875Z',
    category: '[category-id]',
    lastUpdatedHash: '4dd02849e3f5a032a827077f91c4d1506c6cfbd9',
    updates: [],
    _id: '[id]',
    next: { pages: [], description: '' },
    link_external: false,
    link_url: '',
    sync_unique: '',
    hidden: true,
    api: { auth: 'required', params: [], url: '', method: 'get' },
    isReference: false,
    order: 999,
    body: '[body-text]',
    excerpt: '',
    slug: '[slug]',
    type: 'basic',
    metadata: { description: '', title: '', image: [] },
    title: '[title]',
    id: '[id]',
    isApi: false } ]
```

**Comment by domharrington** [comment]
Hey!

This program is intended to be used from a CLI. I would recommend using our HTTP API directly if you're planning on parsing anything that it outputs - this will give you valid JSON. 

https://docs.readme.com/reference/docs

It would be quite good for us to support the `--raw` flag across all endpoints in here, and for that to return the JSON response directly from the API. I'll mention this to the team!

Dom
