### ISSUE TITLE
rdme swagger exits with exit code 0 on error

### ISSUE THREAD

**Issue by xadcoh** [readmeio/rdme#11]
## Problem

`rdme swagger` exits with exit code 0 on error

## Steps for reproduce

run `rdme swagger` with invalid json
rdme will return json string with error message and 'There was an error uploading!'
but `echo $?` will return 0

## Environment
rdme 2.2.2
node 8.14.0
alpine linux 3.8 docker container

**Comment by domharrington** [comment]
Thanks for reporting. This has been released as v3.0.0.
