### ISSUE TITLE
Update existing docs and creating new ones in practice

### ISSUE THREAD

**Issue by maxpumperla** [readmeio/rdme#12]
Hi readmeio team (@domharrington),

thanks for your work on this project - love it. I'd like to incorporate `rdme` in a docs project, but have some problems getting started.

_Setup_: I created a new readme.io project and started new docs, `v1.0` and `v1.1` to test functionality. Both have a `Documents` category. I exported and unzipped the project locally to use the CLI with it. `rdme login` works fine. `rdme docs:edit <slug>` works fine (except that it's unfortunate that the slug is not in the markdown header of the doc and you have to look it up for each doc).

_Issue 1_: I can't seem to update existing docs with `rdme docs <folder> --version=<version>`. I changed one of the files in the existing project and ran (file is called ./v1.0/Documentation/sandbox.md)

```bash
╰─$ rdme docs ./v1.0/ --version=v1.0                                                                                                                                                                            
[]
```

The return value doesn't tell me much, but surely the doc does not update. I'm curious what I am supposed to see. If instead I run this (add `Documentation`):

```bash
╰─$ rdme docs ./v1.0/Documentation/ --version=v1.0
Doc validation failed
{ category: 'Path `category` is required.' }
```

I get this interesting `category` error. From the test fixtures I see that for new docs a `category` seems required. But this is an _existing_ one. This latter call seems to correspond to what I see in tests.

_Issue 2_: How do you create new documents in practice? It seems, as shown in tests, that I need the category ID to add a new document. Otherwise it will throw the same error as above. That information is, unlike slugs, not available in the readme.io UI. So the only way I see to retrieve this info seems to be to resort to the HTTP API. Is that correct? If so that makes it very difficult to work only with `rdme`. 

My goal is to manage docs from a GitHub repo, pushing to readme.io through `rdme` for releases. This way it's much easier for me to test and manage code snippets.

**Comment by domharrington** [comment]
Hey @maxpumperla, thanks for checking this out!

Unfortunately (and rather confusingly) the export format is not the same as the format required to import docs via `rdme`. Right now when you export, the markdown file has a name of "<page title>.md" whereas rdme expects it to be "<slug>.md". These things were created at different times and we've not had a chance to match them up quite yet.

As for workarounds for your specific issues:

#### Issue 1
Right now `rdme` only works on flat folder structures: https://github.com/readmeio/rdme/blob/3afc5f46a23587571ebd1c086ac8ca35a33f37ac/lib/docs/index.js#L31-L33

So if the export outputs with the following:

```
v1.0/
  Category1/
    Doc Title.md
  Category2/
    Doc Title.md
```

In order for it to be importable via rdme, it will have to be changed to this:
```
doc-slug-1.md
doc-slug-2.md
```

#### Issue 2
You're correct that you need to fetch the category id. We do surface this at one point in the app. When you create a new doc, you'll see this button:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/848223/52822840-bf414000-3067-11e9-98ba-86c088c5e510.png">

Clicking that will reveal a tutorial which gives you your api key as well as a snippet that contains the current category id:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/848223/52822876-d41dd380-3067-11e9-819c-21ad68d032b6.png">

I've added these problems to our feature request backlog: https://readmeio.canny.io/feature-requests/p/make-export-and-import-formats-consistent

I apologize that this much worse than it should be, i'll push for this to get fixed. Once you've set it up though it should be fairly painless to update and resync.

Please let me know if you need any more assistance!

**Comment by maxpumperla** [comment]
@domharrington thanks so much for your detailed response. that helps a lot. tbh, I have a ton more issues like these. I'll add new issues to make it easier for you to follow up (I know how difficult issue mgmt can be).

Unfortunately, my JS is pretty non-existent. It might be faster for me to build a Python library that fixes my issues (given current limitations of the HTTP API). I'll keep you posted, but since I suffer from chronic NIH syndrome I might just do that.

**Comment by domharrington** [comment]
Happy to help in any way I can!

**Comment by maxpumperla** [comment]
@domharrington for lack of a better place to share, here is `pyreadme`:
https://github.com/maxpumperla/pyreadme

Nothing fancy, but easier for me to extend from. Maybe interesting for you and team. I'll share my progress regarding managing projects from GitHub as I go. Apart from the infamous "category slugs" this seems totally doable and might be interesting for other non-clickers.

**Comment by domharrington** [comment]
Thanks Max! This looks great, will share it internally.

Thanks again for your feedback as well, it's really helpful.
