### ISSUE TITLE
rdme swagger command throws error

### ISSUE THREAD

**Issue by ergunsh** [readmeio/rdme#166]
Hey there,

I can't update our swagger definitions using the CLI right now. When I run `rdme --key=<readme-key> --id=<readme-docs-id> swagger main.yaml` it gives the error `Cannot read property 'indexOf' of undefined`.

After a bit of investigation, I've found out that this can be related to your API. The `PUT /api-specification/:specId` endpoint returns 500 with `{"error":"Cannot read property 'indexOf' of undefined"}` body from the call made with CLI.

**Comment by ergunsh** [comment]
This seems to be fixed now, thanks!

**Comment by erunion** [comment]
Ah sorry about that, we pushed some updates to our search infrastructure that caused some failures when saving updates across the site.
