### ISSUE TITLE
Can I set `parentDoc` etc. of a document with your API?

### ISSUE THREAD

**Issue by maxpumperla** [readmeio/rdme#17]
When retrieving document details via `/api/v1/docs/slug` I see a lot of juicy stuff that's reflected in the UI, for instance:

```
"parentDoc":"5c653f75f49e7d00516eb11e","__v":0,"updates":[],"next":{"pages":[],"description":""}
```

However, if I export a document I get a markdown doc with headers that does not contain that info. The header will usually just have title and category. All the other good stuff seems to be associated with the slug, but is stored somewhere server-side.

So the question is, can I update these other properties as well through API calls? I'm seeing `options` here:

https://github.com/readmeio/rdme/blob/master/lib/docs/edit.js#L63-L67

but I can't confirm what optional parameters do on the backend. i.e. is this intended / does it work:

```
slug = 'xxx'
version = 'v1.0'
url = host + "/api/v1/docs/" + slug
headers = {
    'x-readme-version': version,
    'content-type': "application/json",
}
# Note: headers need to be extracted from yaml
payload = json.dumps({
    'title': "xxx",
    'category': "5c653f7f24320544d0",
    'body': "Foo can be installed in two ways. bla bla"
    'parentDoc': "other-slug" # <-- TODO like this?
})

response = requests.request("PUT", url, data=payload, headers=headers, auth=auth)
print(response.text)
```

**Comment by domharrington** [comment]
Hey!

We have no restrictions on the properties that can be updated via the API, apart from the project.

Specifically, you can set the `parentDoc` via the API using the id of the page (similarly to the category).

If you follow the tutorial in the UI when you create a child doc, you'll see an example of this in the markdown sample:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/848223/52877100-e5212000-310d-11e9-80f4-3ff1b609608d.png">

Dom

**Comment by maxpumperla** [comment]
@domharrington ok, so just to be 100% clear here I don't stumble on another "a vs. b slug" problem, when you say

```
the API using the id of the page (similarly to the category).
```

you mean the ID that I see in the details of that document, correct (not the doc slug, or anything else)?

**Comment by domharrington** [comment]
Correct yes. `parentDoc` would be the id of the doc that was being set as the parent. The `category` is the id of the category.

Definitely we want to switch to using the slugs for this.
