### ISSUE TITLE
Remove critical npm vulnerability

### ISSUE THREAD

**Issue by michaelfarrell76** [readmeio/rdme#18]
![Screen Shot 2019-03-12 at 8 18 02 PM](https://user-images.githubusercontent.com/10264973/54251309-081fd380-4504-11e9-95d9-257077296758.png)

I understand that this `open` package may be useful for login, but having the critically severe vulnerability warning in the npm warnings makes this package impossible to use in CI for anybody that has strict vulnerability standards.

**Comment by gkoberger** [comment]
@domharrington , any thoughts on this?

**Comment by gkoberger** [comment]
Okay, should be fixed in rdme@3.0.1! Let me know if you run into any others :)

**Comment by michaelfarrell76** [comment]
Yuo did the trick!!! really appreciate it :)

**Comment by gkoberger** [comment]
🤗
