### ISSUE TITLE
Unable to resolve $ref pointer

### ISSUE THREAD

**Issue by v1bh0r** [readmeio/rdme#196]
Does Readme support external references in an OAS file?
Eg. https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-8-splitting-specification-file/#reference-to-a-file-in-a-folder

I'm getting the following error when I refer to another file
````
Unable to resolve $ref pointer "paths/pets.yml"
````

**Comment by erunion** [comment]
We unfortunately don't right now, so references will need to be contained within the same file.

It's on my roadmap for the next month to get external reference support in `rdme`.

**Comment by erunion** [comment]
Keeping this open as a todo

**Comment by erunion** [comment]
This was added earlier this summer!
