### ISSUE TITLE
Setting the "parentDoc" for a document to itself prevents you from deleting that document

### ISSUE THREAD

**Issue by djweber** [readmeio/rdme#234]
Hi,

Love the product so far! That being said, I did encounter one issue: during one test run of a CICD integration, I mistakenly set the `parentDoc` of a document to be its own ID:

```
GET https://dash.readme.io/api/v1/docs/{doc-slug}

{
    ...
    "parentDoc": "5f46b08d5688b911ed64801a",
    "id": "5f46b08d5688b911ed64801a",
}
```

This causes the document to not even show in the ReadMe dash under its category. However, it can be retrieved via the API. Also, you cannot delete the document from the system due to the circular reference:

```
DELETE https://dash.readme.io/api/v1/docs/{doc-slug}

{
    "error": "INTERNAL_ERROR",
    "message": "Unknown error (You cannot remove pages with children)",
    ...
}
```

This also prevents me from being able to delete the category containing the doc, since that document is stuck in there.

To work around this issue, you can make a `PUT` request and set the `parentDoc` of the API to `null`. Then, you can delete it. I believe it would be a better approach to have the API not allow cyclical references for `parentDoc`.

This is probably less of a CLI issue and more of an API issue, but this seemed like the next best place to report it.

Thanks for your time!

**Comment by erunion** [comment]
Thanks @djweber, we'll move this ticket to our internal tracker and handle it.
