### ISSUE TITLE
Unable to update docs using docs command

### ISSUE THREAD

**Issue by rayraffi** [readmeio/rdme#251]
Hi, I am trying to use the docs command to create or update our guides in an automated way in a CI pipeline, but instead of updating a doc that exists, the CLI keeps creating a new one. I have the slug for the doc defined in the front matter of the markdown file and the file name matches this slug. 

Looking at the source code for the command [here](https://github.com/readmeio/rdme/blob/master/cmds/docs/index.js) it looks like when the `updateDoc` function is called it gets passed undefined for `existingDoc` parameter, which should raise an error in the if-check in the beginning of the function, which makes it always create the doc instead.

**Comment by jesseyowell** [comment]
Hi there! There is definitely a bug with sync'ing diffrent types of doc slugs. Here's the format that works without issue:
`---
title: "files"
excerpt: "these are my files"
slug: "files"
category: 6039419eee15f1005fb57099
---

This is my page on files!`

The occurs when you're adding in a hyphen tp the slug, so we'll need to fix that functionality!
