### ISSUE TITLE
Add support for changelog endpoints

### ISSUE THREAD

**Issue by alexylew** [readmeio/rdme#278]
The readme API includes endpoints that relate to changelogs but the CLI doesn't currently support them. Would the maintainers be open to a PR that added support? Are there contributor guidelines?

**Comment by kanadgupta** [comment]
Hi @alexylew, I just realized that nobody answered your questions, apologies! Yes we are open to PRs—you can view our contributing guidelines [here](https://github.com/readmeio/rdme/blob/main/CONTRIBUTING.md). We haven't had the bandwidth to get to this but if you do take this on, we recommend following the patterns we use for syncing directories of Markdown files. [This file](https://github.com/readmeio/rdme/blob/main/src/cmds/docs/index.js) contains most of that logic. Thanks!
