### ISSUE TITLE
Add support for swagger and OAS file validation

### ISSUE THREAD

**Issue by pawarrchetan** [readmeio/rdme#326]
It would be great to have a upload validation feature with the rdme CLI as this will greatly help integrate the rdme CLI utility in the existing CI/CD workflows.

**Comment by erunion** [comment]
We can/should probably add this in with an `openapi:validate` or `swagger:validate` command.

**Comment by erunion** [comment]
We now have a `validate` command with rdme@6.1!

![screen_shot_2021-12-09_at_1 00 38_pm](https://user-images.githubusercontent.com/33762/145476178-7b4e1688-8d4c-4b4c-879c-c579f7d54de8.png)
