### ISSUE TITLE
Is there a way to create subpages using the cli?

### ISSUE THREAD

**Issue by trishahanlon** [readmeio/rdme#368]
I see on the Readme.io documentation page, there is a way to create subpages using a [cURL command](https://github.com/readmeio/rdme/issues/new), I was wondering if there was a similar command in the readme CLI to create subpages?

**Comment by garrett-wade** [comment]
@kanadgupta @erunion, has this work been prioritized, would be will to make a PR if not. Thoughts are adding an extra parameter to the great matter to support a slug for category and a slug for page, together they can be formed to upload a sup-page.

**Comment by kanadgupta** [comment]
Hi all! Thanks for your patience here. To make a page the child of another page, you can do one of the following:
1. Include the `parentDoc` property, where the value is the `id` of the parent doc. Check out the parameters in our [Create Doc endpoint](https://docs.readme.com/reference/createdoc) for more info on this.
2. You can rearrange the page within the dashboard after the initial sync. As long as you don't include the `parentDoc` property, subsequent syncs should preserve the parent-child hierarchy. We use this technique for our Markdown docs. See [the page in GitHub here](https://github.com/readmeio/markdown/blob/next/docs/syntax-extensions.md) and [the resulting page in ReadMe here](https://github.com/readmeio/markdown/blob/next/docs/syntax-extensions.md).

**Comment by garrett-wade** [comment]
@kanadgupta Was just about to follow up that I realized you can just add the parentDoc param already. Thanks and sorry fo the confusion!

**Comment by kanadgupta** [comment]
No problem @garrett-wade! If y'all have any other questions, feel free to open another issue. Thanks!
