### ISSUE TITLE
`rdme versions --raw` doesn't output the raw JSON response

### ISSUE THREAD

**Issue by magni-** [readmeio/rdme#369]
It instead outputs the JS object version (the keys aren't stringified), which means you can't easily pipe it to a tool such as `jq`.

The reason I'm doing this in the first place is because it looks like there is no command to get the main version? ~And the reason I'm doing that is because it looks like there is no way to sync an API reference using the main version (without knowing which version is main)?~ _(edit: I had a typo in the environment variable I was passing to the `--id` parameter, which I why I was seeing a prompt when running `rdme openapi ...` 🤦🏼)_

If either of these assumptions are wrong, that'd make my life easier 😅 But even in that case it'd probably be better for `--raw` to output raw JSON for any other use cases people might have.

**Comment by kanadgupta** [comment]
Thanks for the feedback @magni-, fixed this in #404! You're correct that we don't have a command to only return the main version, but thanks to your suggestion, this should do the trick:
```sh
rdme versions --raw | jq '.[] | select(.is_stable == true)'
```
