### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by jdecool** [readmeio/rdme#388]
Currently we can only upload OpenAPI specification written in JSON.

It would be great to allow upload YAML specification.

**Comment by erunion** [comment]
@jdecool rdme supports uploading YAML OpenAPI definitions, are you referring instead to our API?

**Comment by jdecool** [comment]
Hi @erunion thanks for your response.

I've make a try and it works ! I think it's not possible because it's not describe in the project README, but it's 👌🏼 

Thanks.
