### ISSUE TITLE
6.0.0 won't install on the `node:lts-alpine` image

### ISSUE THREAD

**Issue by magni-** [readmeio/rdme#401]
We sync our API docs on `node:lts-alpine` images via CircleCI. This has worked fine since we first started doing it in late September (meaning using `rdme` versions 5.1.4 and 5.2.0), but now blows up with the new 6.0.0 release.

The error message from `npm` is rather cryptic:
```
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Here are the full logs for the failed 6.0.0 install, along with logs from a subsequent successful install of 5.2.0 in the same VM.

[npm-install-g-5-2-0.log](https://github.com/readmeio/rdme/files/7666045/npm-install-g-5-2-0.log)
[npm-install-g-6-0-0.log](https://github.com/readmeio/rdme/files/7666046/npm-install-g-6-0-0.log)

I tried taking a look at both of these to see if there was anything obvious but couldn't spot it. `timing idealTree Completed` shows up in the 5.2.0 log but not the 6.0.0 log. I don't know what that line represents 🤷🏼

**Comment by erunion** [comment]
Looks like the 6.0 install is using npm@8.1.2 but the 5.2 one was using npm@8.2. Do you mind retrying the 6.0 install with npm@8.2 and sending me the log from that if it fails again?

**Comment by magni-** [comment]
Ah yep, I noticed `npm` wasn't at the latest and tried updating that to see if it fixed it—it didn't. Here's a full log:
[npm-install-g-6-0-0.log](https://github.com/readmeio/rdme/files/7672290/npm-install-g-6-0-0.log)

**Comment by erunion** [comment]
Seems this is happening because rdme depends on [oas](https://npm.im/oas), which depends on [@readme/openapi-parser](https://npm.im/@readme/openapi-parser) and that's loading in a fork we have of [@apidevtools/json-schema-ref-parser](https://npm.im/@apidevtools/json-schema-ref-parser) and though that dependency there is set to `github:erunion/json-schema-ref-parser#fix/dates-as-strings` npm is loading it with git+ssh and the `node:lts-alpine` image doesn't have git installed.

I'll publish that fork to npm like a proper package and publish a 6.0.1 release of rdme but in the meantime this image was able to install rdme:

```dockerfile
FROM node:lts-alpine

ADD . /src
WORKDIR /src

RUN apk add --no-cache git

RUN git --version
RUN npm install rdme
```

**Comment by erunion** [comment]
@magni- With [6.0.1](https://github.com/readmeio/rdme/releases/tag/6.0.1) this appears to be working again:

```
❯ docker-compose up
[+] Building 0.5s (9/9) FINISHED                                                                                                 
 => [internal] load build definition from debug.Dockerfile                                                                  0.0s
 => => transferring dockerfile: 37B                                                                                         0.0s
 => [internal] load .dockerignore                                                                                           0.0s
 => => transferring context: 2B                                                                                             0.0s
 => [internal] load metadata for docker.io/library/node:lts-alpine                                                          0.4s
 => [internal] load build context                                                                                           0.0s
 => => transferring context: 75B                                                                                            0.0s
 => [1/4] FROM docker.io/library/node:lts-alpine@sha256:a9b9cb880fa429b0bea899cd3b1bc081ab7277cc97e6d2dcd84bd9753b2027e1    0.0s
 => CACHED [2/4] ADD . /src                                                                                                 0.0s
 => CACHED [3/4] WORKDIR /src                                                                                               0.0s
 => CACHED [4/4] RUN npm install rdme@6.0.1                                                                                 0.0s
 => exporting to image                                                                                                      0.0s
 => => exporting layers                                                                                                     0.0s
 => => writing image sha256:e92b5bbcd9c9bc4f1d93134559c1ad9a3206b6ea6480119cf0d8d7a3c757de23                                0.0s
 => => naming to docker.io/library/rdme-docker_rdme_debug                                                                   0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 2/2
 ⠿ Network rdme-docker_default         Created                                                                              0.1s
 ⠿ Container rdme-docker_rdme_debug_1  Created                                                                              0.1s
Attaching to rdme_debug_1
rdme_debug_1  | 6.0.1
rdme_debug_1 exited with code 0
```

Tested with this files:

<details>
<summary>Dockerfile</summary>

```dockerfile
FROM node:lts-alpine

ADD . /src
WORKDIR /src

RUN npm install rdme@6.0.1
```
</details>

<details>
<summary>docker-compose.yml</summary>

```yml
version: '3'
services:
  rdme_debug:
    build:
      context: .
      dockerfile: debug.Dockerfile
    command: "npx rdme --version"

```
</details>

Let me know if you still have any problems and thanks for letting us know about this!

**Comment by magni-** [comment]
Thanks for the speedy fix!
