### ISSUE TITLE
Better error handling for incorrect categories added

### ISSUE THREAD

**Issue by jesseyowell** [readmeio/rdme#425]
It's possible to create a Markdown file that is "mostly" valid but may have an incorrect character in the `category:` field. When sync'ing with docs, these files are skipped with no error. For example:

```
---
title: "Update an existing pet"
slug: "updatepet"
category:·6154c7c5b68688042eee057b
---
This is body text for the page
```

If you attempt to sync this file, you will get an ambiguous status:

```
❯ npx rdme docs test_folder
✔ Would you like to use an existing version or create a new one to associate with your OAS file? · update
✔ Select your desired version · 1.0
[]
```

**Comment by kanadgupta** [comment]
I'm fairly sure this was fixed with https://github.com/readmeio/rdme/pull/421. @jesseyowell can you confirm?
