### ISSUE TITLE
Docs duplicated and not sync'ed

### ISSUE THREAD

**Issue by cbarlow1993** [readmeio/rdme#445]
I use the following command to attempt to sync my documents folder with the readme backend. 

`npx rdme docs ./v1.0/ --version=1.0  --key API_KEY-GOES_HERE`

The output of my versions is 

```
[
  {
    version: '1.0',
    version_clean: '1.0.0',
    codename: '',
    is_stable: true,
    is_beta: false,
    is_hidden: false,
    is_deprecated: false,
    _id: '620a5ec4dbe8a-half-removed,
    createdAt: '2022-02-14T13:53:08.575Z'
  }
]
```
Everytime I sync them with the above command, it duplicates the file and increments the slug with -1, -2, etc.
<img width="260" alt="Screenshot 2022-02-21 at 08 38 33" src="https://user-images.githubusercontent.com/7342008/154918306-bf077a67-210c-444b-a0d0-97d992f0d171.png">

My page headers are as follows:

```

---
title: "Best Practices"
excerpt: "brief description of best pracitces"
category: "620a5ec4dbe8a70-valid-category-id"
---
Some content here
```

There is no `--verbose` or `--debug` option to support with debugging.

Version 6.4.0

**Comment by kanadgupta** [comment]
Hi @cbarlow1993! Sorry for the troubles. We actually have debug support in progress in #446. Once that's released, we'd love to see what the log results look like. In the meantime, do you mind reaching out to support@readme.io with your project and category information?

**Comment by kanadgupta** [comment]
Hey @cbarlow1993 — we just shipped [`v7` of `rdme`](https://github.com/readmeio/rdme/releases/tag/7.0.0), which includes improved docs command output, [a `--dryRun` flag](https://docs.readme.com/docs/rdme#dry-run-mode), and [a host of other debugging options](https://docs.readme.com/docs/rdme#troubleshooting). If you're still having troubles, feel free to open another issue or contact us at [support@readme.io](mailto:support@readme.io)!

**Comment by cbarlow1993** [comment]
Hi @kanadgupta, I took some time to look at what was going on using the debug feature and I can now report the following.

It's to do with the filenames.

If I have filename "Getting Started.md", when the code makes a request to see if the Document already exists, the slug that it check is "https://dash.readme.com/api/v1/docs/best practices". However, when parsing the filename to create the slug, it drops the space in the file name and replaces it with a -... "getting-started.md".

As a result, each time it creates a new document with an incrementing -1, -2 etc.

**Comment by kanadgupta** [comment]
@cbarlow1993 since your file name contains characters that can't be in page slugs (e.g. spaces), you should specify the `slug` via your YAML front matter. See our docs on the subject here: https://docs.readme.com/docs/rdme#specifying-page-slugs
