### ISSUE TITLE
Github actions secrets correction in documentation

### ISSUE THREAD

**Issue by paulcjh** [readmeio/rdme#470]
Currently in [the main sync docs here](https://github.com/readmeio/rdme/blob/main/documentation/rdme.md) the method used for using github secrets doesn't work. It requires the addition of `$` at the start to yield the secret:

Old
```
- uses: readmeio/rdme@RDME_VERSION
  with:
    rdme: openapi [path-to-file.json] --key={{ secrets.README_API_KEY }} --id={{ secrets.README_API_DEFINITION_ID }}
```
New
```
- uses: readmeio/rdme@RDME_VERSION
  with:
    rdme: openapi [path-to-file.json] --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }}
```

**Comment by kanadgupta** [comment]
Yikes, thanks for the catch @paulcjh! Fixed in #471 🎉
