### ISSUE TITLE
Cannot find module 'ajv/dist/core'

### ISSUE THREAD

**Issue by falexandrou** [readmeio/rdme#496]
Hello 👋 

I recently installed `rdme` as a dev dependency, but when I tried to run it for the first time, I got the following error:

```
Cannot find module 'ajv/dist/core'
Require stack:
- /src/node_modules/ajv-draft-04/dist/index.js
- /src/node_modules/@readme/openapi-parser/lib/validators/schema.js
- /src/node_modules/@readme/openapi-parser/lib/index.js
- /src/node_modules/oas-normalize/index.js
- /src/node_modules/rdme/src/lib/prepareOas.js
- /src/node_modules/rdme/src/cmds/openapi.js
- /src/node_modules/rdme/src/lib/commands.js
- /src/node_modules/rdme/src/lib/help.js
- /src/node_modules/rdme/src/index.js
- /src/node_modules/rdme/bin/rdme
```
Node version is  v14.18.3 and npm version is 6.14.15

I tried running it in a container (node:14-alpine) that had nothing else installed but Node and NPM, and it seemed to be working.
My assumption is that this is due to the fact I have other dependencies that require lower versions of `ajv`:

```
+-- babel-loader@8.1.0
| `-- schema-utils@2.6.5
|   `-- ajv@6.12.0
+-- cache-loader@4.1.0
| `-- schema-utils@2.6.2
|   `-- ajv@6.10.2
+-- css-loader@3.6.0
| `-- schema-utils@2.7.0
|   `-- ajv@6.12.4
+-- eslint@6.8.0
| +-- ajv@6.12.6  deduped
| `-- table@5.4.6
|   `-- ajv@6.11.0
+-- eslint-loader@3.0.3
| `-- schema-utils@2.6.2
|   `-- ajv@6.10.2
+-- file-loader@6.0.0
| `-- schema-utils@2.6.5
|   `-- ajv@6.12.0
+-- jsdom@16.2.1
| `-- request@2.88.2
|   `-- har-validator@5.1.3
|     `-- ajv@6.12.6  deduped
+-- mini-css-extract-plugin@0.9.0
| `-- schema-utils@1.0.0
|   `-- ajv@6.9.1
+-- null-loader@4.0.0
| `-- schema-utils@2.7.0
|   `-- ajv@6.12.2
+-- parallel-webpack@2.6.0
| `-- ajv@4.11.8
+-- rdme@7.2.0
| `-- oas-normalize@6.0.0
|   `-- @readme/openapi-parser@2.2.0
|     `-- ajv@8.11.0
+-- sass-loader@8.0.2
| `-- schema-utils@2.6.4
|   `-- ajv@6.11.0
+-- style-loader@1.1.3
| `-- schema-utils@2.6.4
|   `-- ajv@6.11.0
+-- terser-webpack-plugin@4.2.3
| `-- schema-utils@3.1.1
|   `-- ajv@6.12.6
`-- webpack@4.43.0
  `-- ajv@6.12.2
```

**Comment by erunion** [comment]
Hi, what version of NPM and Node are you running? We had a similar issue come through to our [api](https://github.com/readmeio/api) library last month (https://github.com/readmeio/api/issues/416) regarding the same `@readme/openapi-parser` dependency and it came down to a the version of npm+node they were using was loading ajv@6 instead of ajv@8.

**Comment by falexandrou** [comment]
I added my Node & NPM version in the description. Installing `ajv@8` as a dev dependency did the trick but it's just a workaround, since the experience of `npx rdme ...` -> error is not ideal.

This looks like an issue with `ajv-draft-04` that this package is using though https://github.com/ajv-validator/ajv-draft-04/issues/4
