### ISSUE TITLE
upload request timed out

### ISSUE THREAD

**Issue by kivanio** [readmeio/rdme#499]
Every time I try to upload my file:
```
rdme openapi swagger/v1/swagger.json --key=yyy --id=xxx
```

it raises:
```
We're sorry, your upload request timed out. Please try again or split your file up into smaller chunks.
```

Where can I find out more informations about it?
Size allowed?
What do?

**Comment by kanadgupta** [comment]
Hi @kivanio! We don't have any documented limits. Would you mind linking to a copy of your spec file so we can reproduce? If you don't prefer to post it publicly, you can [contact our support team](https://github.com/readmeio/.github/blob/main/.github/SUPPORT.md).

**Comment by kivanio** [comment]
@kanadgupta Thank you.
I have contacted the Support.

Same file works when sending by UI.
So It could be an rdme bug.

Validate say it is Ok:
```
rdme validate swagger/v1/swagger.json                                                                    
swagger/v1/swagger.json is a valid OpenAPI API definition!
```

**Comment by hanakslr** [comment]
I am also encountering this issue - our spec file is located here: https://github.com/faradayio/sdk_docs/blob/main/static/api.yml (we do some post processing before upload to remove the `const:` fields)

**Comment by dabrowne** [comment]
+1 on this. Our schema file is not big (~147KB):

```sh
> rdme openapi --key=$README_TOKEN --id=xxxxxxx developers/readme/xxxxxxx-spec.yml


We're sorry, your upload request timed out. Please try again or split your file up into smaller chunks.
```

```sh
> rdme validate developers/readme/xxxxxxx-spec.yml

developers/readme/xxxxxxx-spec.yml is a valid OpenAPI API definition!
```

**Comment by dabrowne** [comment]
Ok, easy resolution for me! Our API key disappeared/was revoked. I generated a new API key and we're back up and running again.

Do readme API keys automatically expire at some time? I notice that the new API key begins with `rdme_` and is much longer, whereas our previous key had no prefix. Has there potentially been some automated revocation of the older style keys which is causing this problem?

**Comment by glassblowerscat** [comment]
> Ok, easy resolution for me! Our API key disappeared/was revoked. I generated a new API key and we're back up and running again.
> 
> Do readme API keys automatically expire at some time? I notice that the new API key begins with `rdme_` and is much longer, whereas our previous key had no prefix. Has there potentially been some automated revocation of the older style keys which is causing this problem?

ReadMe had a security incident that caused them to revoke all API keys; you can [read about it in here](https://docs.readme.com/changelog/api-key-incident-may-2022)

**Comment by glassblowerscat** [comment]
+1 on this, even after checking that my API key was up to date and running `rdme validate` on the file. I'm actually syncing two different files to two different ReadMe projects using the same GitHub Action. One of them always fails with the above message, but the other one succeeds. Even if reverse the order in which I do the sync, I get the same result.

**Comment by erunion** [comment]
Hi all, we're working on some improvements to these upload timeouts and we should have some work done on it over the next couple weeks. In the meantime all we can really recommend is that you either keep trying to upload them and it might eventually work, or chunk your definitions into a two smaller definitions. Definitely not ideal, and the fixes we're working on will alleviate all of this pain, but until then this is the best we can work with. I'm sorry. 😞 Improvements are coming soon!

**Comment by glassblowerscat** [comment]
My issue has been resolved by support. Here's what they had to say about it:

> I think this is due to the fact your default definition is listed as Additional API Settings. This happens if you originally create a definition, and then move endpoints/pages out of that category, then delete the original category.
﻿
> ﻿To resolve this, I think we can probably (with your permission!) delete this Additional API Setting and have you redo the sync command.

After they performed this action, my sync operations worked as expected
