### ISSUE TITLE
rdme validate does not follow relative paths in docs when called on nested API definition

### ISSUE THREAD

**Issue by erikwlarsen** [readmeio/rdme#507]
Hello! Thanks for the great tool.

I've found that the rdme tool expects that it is invoked in the same directory as the openAPI definition entrypoint. When using the rdme github action, I provide a path to a nested API definition, like this:
```yaml
- name: Push new docs
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi docs/public/api.yaml --key=${{ secrets.README_API_KEY }} --id={{ secrets.README_ID }}
```
The repo structure (simplified a bit) looks like this:
```
Main/
  docs/
    public/
      api.yaml
      paths/
        routes.yaml
```

Within the `api.yaml` file I have a ref that looks like this:
```/route/{route_token}:
    $ref: "./paths/routes.yaml#/~1route~1{route_token}"
```

which results in this error like this when running github actions:
```
Error: Error opening file "/home/runner/work/Main/Main/paths/routes.yaml" 
```

I'm able to recreate this error locally by invoking the `rdme` CLI:
```bash
mkdir docs
mkdir docs/nested
touch docs/nested/main.yaml
touch docs/nested/ref.yaml
```
main.yaml looks like this:
```yaml
openapi: 3.0.0
info:
  title: API docs
  version: 1.0.0
paths:
  /my-path:
    $ref: "./ref.yaml#/~1my-path"
```
and ref.yaml looks like this:
```yaml
/my-path:
  get:
    responses:
      '200':
        description: empty response
```
By running `rdme validate docs/nested/main.yaml`, I can get the same error I'm seeing in github actions:
```
Error opening file "/Users/me/projects/ref.yaml"
ENOENT: no such file or directory, open '/Users/me/projects/ref.yaml'
```
Validation works correctly if run within the same directory as the main definition (`cd docs/nested && rdme validate main.yaml`).

Is there any workaround for using the `rdme` github action in a directory structure that doesn't have the open API spec at the root level? I haven't found any way to set the directory beyond just providing a path to the file.

**Comment by kanadgupta** [comment]
Hi @erikwlarsen! Have you tried using the `--workingDirectory` option? You can view the docs on that option here: https://github.com/readmeio/rdme#override-the-working-directory

**Comment by erikwlarsen** [comment]
well that's embarrassing 🤦 will close this, thanks for the quick response @kanadgupta !
