### ISSUE TITLE
How I can delete all versions in a project using rdme CLI ?

### ISSUE THREAD

**Issue by Ebeid** [readmeio/rdme#509]

**Comment by kanadgupta** [comment]
Hi @Ebeid—you should be able to write a script to delete most of your versions using a combination of [this command](https://github.com/readmeio/rdme#get-all-versions-associated-with-your-project) and [this command](https://github.com/readmeio/rdme#delete-a-version) but ReadMe projects require at least one version so it isn't possible to delete all versions.
