### ISSUE TITLE
Sync files which only has `title` and `category` attributes in the markdown files

### ISSUE THREAD

**Issue by tonilopezmr** [readmeio/rdme#539]
It could be interesting to have a configuration flag to only sync Markdown files which match the requirements to be uploaded. 

*Why is this useful?* In your example you have a  `documentation` directory, but in some repositories, the docs are spread on different directories. Instead of running the CLI command multiple times indicating those directories, it could be interesting to indicate the root directory, and mark the flag like `--silent-continue` instead of throw an error because `README.md` doesn't have the attribute `category`.

What do you think about It?

**Comment by kanadgupta** [comment]
Thanks for the suggestion @tonilopezmr! We've been ideating[^1] docs syncing improvements for some time now (e.g. ignore patterns, zero-config) and addressing this type of use case is on our radar. Don't have any specifics or a timeline for you just yet but we'll definitely take your feedback into consideration!

[^1]: internal note: see RM-4421

**Comment by tonilopezmr** [comment]
INMO having this kind for flag/config for now it could be a nice to have in the meantime you are adding more complete features as `ignore patterns` and `zero-config` features.

Thank you @kanadgupta and readme.io team! 💪
