### ISSUE TITLE
Command Line Update doesn't support --create or --update command like described in readme

### ISSUE THREAD

**Issue by nweave03** [readmeio/rdme#601]
rdme openapi <file> --version=<version> --key <key> --create

Unknown option: --create

rdme openapi <file> --version=<version> --key <key> --update

Unknown option: --update

**Comment by erunion** [comment]
Hi, these new arguments are coming to our v8 release that we're working on. The docs you see in the main repository readme are for that version, but the docs on https://www.npmjs.com/package/rdme are for the non-beta current release.

**Comment by nweave03** [comment]
got it, thanks!
