### ISSUE TITLE
Question: validate command to report all validation issues instead of one at a time

### ISSUE THREAD

**Issue by Ebeid** [readmeio/rdme#638]
Not sure if there is a way for **validate** to report back all validation issues/violations instead of one at a time.

**Comment by kanadgupta** [comment]
Looks to be an upstream issue with how validation errors are returned in [`openapi-parser`](https://github.com/readmeio/openapi-parser). We'll dig into this!

**Comment by erunion** [comment]
This is now resolved in https://github.com/readmeio/rdme/pull/639, https://github.com/readmeio/openapi-parser/pull/135, https://github.com/readmeio/oas-normalize/pull/220 and will be part of out upcoming v8 release.

**Comment by Ebeid** [comment]
@erunion when v8 release scheduled ?

**Comment by kanadgupta** [comment]
@Ebeid most likely in a couple weeks!

**Comment by kanadgupta** [comment]
@Ebeid I've tagged a new beta release if you wish to play around with it.

```sh
npm install rdme@next
```
