### ISSUE TITLE
failing with "fatal: could not read Username for 'https://github.com'" after 8.0.0 release

### ISSUE THREAD

**Issue by david-wolgemuth** [readmeio/rdme#649]
hello,

our CI started failing after the 8.0.0 release today while running:

```sh
npx --yes rdme docs $PATH --version=$VERSION --key=$KEY
```

giving the following output:

```
git: 'credential-gcloud.sh' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': No such device or address
```

(running within Google Cloud Build, which is why I assume it is looking for `credential-gcloud.sh`)

we pinned it back to 7.x for the time being, not sure the context around rdme using git

**Comment by david-wolgemuth** [comment]
Thanks for the quick turnaround @kanadgupta , looking at that lib, it seems GCP sets almost nothing.. We can manually `export CI=true` 👍 

https://github.com/npm/ci-detect/blob/995830e84f7aff0ff1d5e3135773f7561b390367/lib/index.js#L50-L51

**Comment by kanadgupta** [comment]
Sounds good @david-wolgemuth! [v8.0.1](https://github.com/readmeio/rdme/releases/tag/8.0.1) is now released with a potential fix. Let me know if that addresses the issue — ideally we shouldn't require folks using GCP to manually export a variable like that.
