### ISSUE TITLE
proxy configuration

### ISSUE THREAD

**Issue by maxiz12** [readmeio/rdme#680]
I am trying to upload a json document to our developer portal behind our company proxy.
However, when try to do the upload, I get the following error in our gitlab pipeline:
request to https://dash.readme.com/api/v1/version failed, reason: connect ETIMEDOUT 172.67.215.249:443
 
The timeout seems to happen because of our firewall blocking the connection.
Does the rdme CLI tool support proxy configuration?
Something like 
HTTP_PROXY=xxx
HTTPS_PROXY=xxx

**Comment by kanadgupta** [comment]
Hi @maxiz12, we just shipped support for this via the `HTTPS_PROXY` environmental variable. We'll be tagging a release soon. Thanks!
