### ISSUE TITLE
rdme versions output isn't entirely JSON

### ISSUE THREAD

**Issue by theholla** [readmeio/rdme#697]
Our company has some automation around the `rdme versions` command. I saw that as of https://github.com/readmeio/rdme/pull/603, raw JSON should be the new default and the `--raw` is no longer available.

The issue I'm running into is that before outputting the raw JSON, the command outputs one line about auth: `🔑 someone@company.com is currently logged in, using the stored API key for this project: projectname`.

I wanted to check whether this is intended, and if so if there's a way to disable the auth line? Otherwise we can update our automation to handle.

**Comment by kanadgupta** [comment]
Great to hear! We definitely recommend using the `--key` option in automated workflows as opposed to `rdme login` since API keys are much safer to use than passwords. I'll make a note of this in our docs. Sorry for the disruption to your workflow!
