### ISSUE TITLE
rdme CLI requires connection to remote git repo

### ISSUE THREAD

**Issue by liaz-af** [readmeio/rdme#704]
I'm running the CLI on a repo which has a remote behind a VPN.
If the VPN is not connected and repo is accessible I'm getting this error:
```
fatal: unable to access 'https://XXXX.appsflyer.com/YYYYYYY/ZZZZZ.git/': Could not resolve host: XXXX.appsflyer.com
```

**Comment by kanadgupta** [comment]
Apologies for the trouble, @liaz-af! I just tagged `8.2.1`, which should handle those errors properly. If you're still seeing issues, please let us know!

https://github.com/readmeio/rdme/releases/tag/8.2.1
https://www.npmjs.com/package/rdme/v/8.2.1
