### ISSUE TITLE
Prune command doesn't remove child pages (and their parent pages)

### ISSUE THREAD

**Issue by colmdoyle** [readmeio/rdme#710]
When pruning docs, the relevant block of code queries `getCategoryDocs` which returns top level pages, but not the child pages inside that category, meaning the command doesn't cascade out and detect child pages for deletion.

## Repro

1. Create a category with a page, and a child page of that page.
2. Sync it to Readme
3. Delete the files from your local filesystem
4. run `rdme docs:prune [path-to-directory-of-markdown]`
5. See that childPage is still on readme, as is the parent doc

(step 5 is kind of expected because you can't have a hanging page like that, but the CLI doesn't even know to delete the child page first)

https://github.com/readmeio/rdme/blob/d1f6c03636d5907afb5584f416fe666c08c7c06d/src/lib/getDocs.ts#L40-L46

**Comment by kanadgupta** [comment]
Thanks for the detailed write-up, @colmdoyle! I briefly investigated and it looks like this is because our [`GET /categories/{slug}/docs`](https://docs.readme.com/main/reference/getcategorydocs) endpoint returns child pages within the `children` array of the respective parent page and we failed to account for that. Here's what the response looks like for [the first category of our docs](https://docs.readme.com/main/docs/intro-to-readme):

```json
[
  {
    "title": "Intro to ReadMe",
    "slug": "intro-to-readme",
    "order": 0,
    "hidden": false,
    "children": []
  },
  {
    "title": "Best Practices",
    "slug": "best-practices",
    "order": 1,
    "hidden": false,
    "children": []
  },
  {
    "title": "Use Cases Overview",
    "slug": "use-cases-overview",
    "order": 2,
    "hidden": false,
    "children": []
  },
  {
    "title": "Features Overview",
    "slug": "features-overview",
    "order": 3,
    "hidden": false,
    "children": []
  },
  {
    "title": "Navigating Your Hub",
    "slug": "navigating-your-hub",
    "order": 4,
    "hidden": false,
    "children": [
      {
        "title": "Search + Search API",
        "slug": "search",
        "order": 0,
        "hidden": false
      },
      {
        "title": "Quick Nav in the API Reference",
        "slug": "quick-nav-api-reference",
        "order": 1,
        "hidden": false
      }
    ]
  }
]
```

**Comment by kanadgupta** [comment]
Just tagged `8.3.1`, which should resolve this issue. Thanks for writing in about this @colmdoyle!

https://github.com/readmeio/rdme/releases/tag/8.3.1
https://www.npmjs.com/package/rdme/v/8.3.1
