### ISSUE TITLE
Error when updating doc using `docs` command with `categorySlug` and `parentSlug`

### ISSUE THREAD

**Issue by garrett-wade** [readmeio/rdme#738]
When running the `rdme docs` command with a doc that has the `categorySlug` and/or `parentSlug` attributes in their front matter the following error is returned:

```
Error uploading docs/Test/Child Doc.md:

We couldn't save this doc (received both a `category` and a `categorySlug`, expecting only one).
```

I think this error occurs because the PUT request made in the `updateDoc()` function of the `syncDocsPath` class merges the existing doc payload with the previous docs payload which causes both the category id and the category slug to be included with the payload.

**Comment by kanadgupta** [comment]
That's exactly what's going on, thanks for the report and the investigation @garrett-wade 💙 opening up a fix shortly!

**Comment by Bradamant3** [comment]
watching this one, encountered the same issue, with `parentDocSlug` only but equivalent error. (Figured issue was something like what @garrett-wade describes but thanks for saving me the chasing it down part ...)

**Comment by kanadgupta** [comment]
@garrett-wade would you be up for reviewing the fix I have in #740?

**Comment by garrett-wade** [comment]
@kanadgupta I can take a look if you want to request a review

**Comment by Bradamant3** [comment]
❤️ that was fast, tysm!

**Comment by kanadgupta** [comment]
No problem! Will be tagging a release in the next day or so, will update this ticket when that happens!

**Comment by kanadgupta** [comment]
Hi all, `8.5.0` is now released which includes a fix for this. Thanks again for writing in!

https://github.com/readmeio/rdme/releases/tag/8.5.0
https://www.npmjs.com/package/rdme/v/8.5.0
