### ISSUE TITLE
Page validation failed (reopen)

### ISSUE THREAD

**Issue by igrek8** [readmeio/rdme#744]
I am using the readmeio/rdme action and discovered this week that it sometimes fails with the following output:

rdme openapi calculate-api-oas-prod.json --key=*** --id=$OPEN_API_SPEC_ID_prod

Validating the API definition located at calculate-api-oas-prod.json...
Staging your API definition for upload...
Updating your API docs in ReadMe...
✖ Updating your API docs in ReadMe...
Error: Unknown error (Page validation failed: project: Path project is required., category: Path category is required.).
This is how I am using the action:

- uses: readmeio/rdme@8.5.0
  with:
    rdme: openapi calculate-api-oas-${{ inputs.STAGE }}.json --key=${{ secrets.README_IO_TOKEN}} --id=$OPEN_API_SPEC_ID_${{ inputs.STAGE }}
If I rerun the failed job, then it sometimes succeeds, so the bug seems to be flaky.

Do you have insights why page validation can fail?

![image](https://user-images.githubusercontent.com/7078731/217840348-f3fac7fb-a760-4d37-88d7-165e0636f6bb.png)

**Comment by igrek8** [comment]
Reopen #743

**Comment by igrek8** [comment]
The url to log: https://docs.readme.com/main/logs/32f6780a-b7cd-474a-a23c-7e86ff79dfe3

**Comment by kanadgupta** [comment]
Hi @igrek8 — we've been making a few database configuration changes lately and this might be related (and likely is not your fault)! A few questions:

1. Do you have an approximate failure percentage rate?
2. When was the last time your workflow threw this error?

**Comment by bennycode** [comment]
Hi @kanadgupta, we have seen an error with it just now (13:28:06 GMT):

```bash
Run /home/runner/work/_actions/readmeio/rdme/8.5.0/bin/rdme openapi calculate-api-oas-prod.json --key=*** --id=$OPEN_API_SPEC_ID_prod
- Validating the API definition located at calculate-api-oas-prod.json...
- Staging your API definition for upload...
- Updating your API docs in ReadMe...
✖ Updating your API docs in ReadMe...
Error: We're sorry, your upload request timed out. Please try again or split your file up into smaller chunks.
Error: Process completed with exit code 1.
```

1. 80-90%
2. Mon, 13 Feb 2023 13:28:06 GMT

**Comment by kanadgupta** [comment]
@bennycode unfortunately timeout errors are a separate issue that are unrelated to the database configuration changes we've been making. We have some broader infrastructure changes coming further down the pipeline that should hopefully address these, but I don't have an ETA on those. I would get in touch at support@readme.io to identify workarounds that are specific to your setup!

**Comment by kanadgupta** [comment]
Closing this out because we haven't heard from you in a bit @igrek8 — let us know if you're still seeing this flaky error!
