### ISSUE TITLE
`rdme help versions:create` throws chalk template error

### ISSUE THREAD

**Issue by jamiebrynes7** [readmeio/rdme#76]
Hi there! 

If I run `rdme versions:create` with no arguments I receive the following output: 

```
jamiebrynes /c/Workspace/Develop/trebuchet  (master)
λ rdme versions:create
No version provided. Please specify a semantic version. See `rdme help versions:create` for help.
```

but running `rdme help versions:create` returns an error:

```
jamiebrynes /c/Workspace/Develop/trebuchet  (master)
λ rdme help versions:create
Found extraneous } in Chalk template literal
```

You then have to dig around in the source to find the options - https://github.com/readmeio/rdme/blob/master/cmds/versions/create.js#L7

**Comment by gratcliff** [comment]
Thanks for bringing this to our attention, Jamie! I'll take a look at it today and report back to you.

**Comment by gratcliff** [comment]
@jamiebrynes7 bundled changes to both your issues into: https://github.com/readmeio/rdme/pull/78. It'll be released today. Closing this out in the meantime!
