### ISSUE TITLE
Page validation failed (reopen)

### ISSUE THREAD

**Issue by bennycode** [readmeio/rdme#766]
We see the `readmeio/rdme` plugin failing again (2023-02-28 18:01 GMT+1, see #743 & #744). We restarted our GitHub Action to upload the OAS file 7x and the error message is either "We're sorry, your upload request timed out" or "Page validation failed".

## Request timed out

```
Run /home/runner/work/_actions/readmeio/rdme/8.5.0/bin/rdme openapi calculate-api-oas-prod.json --key=*** --id=$OPEN_API_SPEC_ID_prod
- Validating the API definition located at calculate-api-oas-prod.json...
- Staging your API definition for upload...
- Updating your API docs in ReadMe...
✖ Updating your API docs in ReadMe...
Error: We're sorry, your upload request timed out. Please try again or split your file up into smaller chunks.
Error: Process completed with exit code 1.
```

## Page validation failed

```
Run /home/runner/work/_actions/readmeio/rdme/8.5.0/bin/rdme openapi calculate-api-oas-prod.json --key=*** --id=$OPEN_API_SPEC_ID_prod
- Validating the API definition located at calculate-api-oas-prod.json...
- Staging your API definition for upload...
- Updating your API docs in ReadMe...
✖ Updating your API docs in ReadMe...
Error: Unknown error (Page validation failed: project: Path `project` is required., category: Path `category` is required.).

https://docs.readme.com/main/reference and include the following link to your API log: 'https://docs.readme.com/main/logs/764b3124-7352-4245-9730-32c64ed99460'.
```

**Comment by kanadgupta** [comment]
Hi @bennycode! I see you're in touch with Darren from our support team about these issues. I think your project is experiencing issues outside of the scope of the `rdme` tool itself so I think reaching out to support is the right move!

I'll be keeping an eye on that ticket and will jump in if need be. Thanks!

**Comment by bennycode** [comment]
**Good News:** We have just discovered that we provided an incorrect `id` for the `rdme openapi` command, which likely resulted in the "Page validation failed" error. Can you modify the error message to provide more specific information, such as highlighting the incorrect id in this scenario?

Unfortunately, we don't know yet where the "upload request timeout" comes from. Our OAS file is just 33 KB.

**Comment by kanadgupta** [comment]
Glad you got it figured out @bennycode! I hear you on the misleading error, sorry about that. We have API definition processing overhauls on our roadmap for this year, which should address both the timeout errors (as I alluded to [here](https://github.com/readmeio/rdme/issues/744#issuecomment-1428073346)) as well as the misleading page validation errors. [Our Changelog](https://docs.readme.com/main/changelog) will be updated as those get released!

The timeout error isn't entirely correlated to file size — there are certain processing scenarios (i.e. certain types of object definitions, polymorphism, references) that might result in a timeout error. Again, should be addressed by our backend overhauls!
