### ISSUE TITLE
`rdme versions:create` doesn't validate the version you give to it 

### ISSUE THREAD

**Issue by jamiebrynes7** [readmeio/rdme#77]
As far as I can tell, readme.io allows versions similar to `4`, `4.0`, `4.0.1`, and `4.0.1-commit-sha` but not something like `test`. 

However, the `rdme` CLI will allow you to attempt to create a version with an invalid version and returns a not particularly helpful error message: 

```
λ rdme versions:create --version=test
√ Which version would you like to fork from? · 1.0.2
√ Would you like to make this version the main version for this project? (y/N) · false
√ Should this version be in beta? (y/N) · false
√ Would you like to make this version public? (y/N) · false
Failed to create a new version using your specified parameters.
```

Ideally, you get a nice 
```
"Error: version `test` invalid, must be ..."
```

before you are even prompted for the extra information

**Comment by gratcliff** [comment]
Thanks for noting this! It's definitely a nice to have, and shouldn't take too much work to implement. I'll have an update your way when it's released :)

**Comment by gratcliff** [comment]
@jamiebrynes7 bundled changes to both your issues into: https://github.com/readmeio/rdme/pull/78. It'll be released today. Closing this out in the meantime!
