### ISSUE TITLE
`rdme openapi {specfile} --create --version {version}` does not work

### ISSUE THREAD

**Issue by cweinberger** [readmeio/rdme#778]
Hi team!

When running the rdme CLI tool to upload spec and create a new version, it does not work.

## Desired command ❌ 

**Command:**
`rdme openapi api-2023-03-20.yml --create --useSpecVersion --key {key}`

**Output:**
```
ℹ️  Using the version specified in your API definition for your ReadMe project version (Mon Mar 20 2023 01:00:00 GMT+0100 (Central European Standard Time))

The version you specified (Mon Mar 20 2023 01:00:00 GMT+0100 (Central European Standard Time)) doesn't match any of the existing versions (0-develop, 0-staging, 2023-02-01, 2023-03-01) in ReadMe.
```
Note: the detected version is also weird, in the spec it is named `2023-03-20`, would expect to not have times in there.

## Minimal command ❌ 

Tried to run a minimal command to rule out it's related to --useSpecVersion but got same result.

**Command:**
`rdme openapi api-2023-03-20.yml --create --version 42 --key {key}`

**Output:**
```
The version you specified (42) doesn't match any of the existing versions (0-develop, 0-staging, 2023-02-01, 2023-03-01) in ReadMe.
```

## More information
```
rdme --version
8.5.0
```

Fails on GH action as well as locally (macOS)

**Comment by kanadgupta** [comment]
Hi @cweinberger, thanks for writing in about this! This looks like an issue with how [we're parsing YAML in `oas-normalize`](https://github.com/readmeio/oas-normalize/blob/main/src/lib/utils.ts#L93) — it appears we're improperly parsing the date string into a JavaScript Date object. Should be a straightforward fix, will post updates here as we have them!

**Comment by cweinberger** [comment]
@kanadgupta thanks for coming back ultra-fast. Please note the other/actual issue as well (unable to create new version while uploading spec). 🙌

**Comment by kanadgupta** [comment]
> Please note the other/actual issue as well (unable to create new version while uploading spec). 🙌

@cweinberger as for this, you'll want to run [`version:create`](https://github.com/readmeio/rdme#create-a-new-version) beforehand. The `openapi` command only works with existing project versions.

**Comment by kanadgupta** [comment]
@cweinberger apologies for the confusion there, the `--create` flag is for creating a new API definition (as opposed to updating an existing API definition), but the version that the API definition is associated with must already exist. Here's a rough diagram of how our data model works (with each of these having a one-to-many relationship):

```mermaid
graph TD;
    A(ReadMe Project)-->B(Version);
    B-->C("API Definition (i.e., an OpenAPI file)");
    C-->D(API reference page);
```

**Comment by kanadgupta** [comment]
You can create multiple specs within the same version by doing something like this:

```
rdme openapi spec1.yaml --version 2.0
rdme openapi spec2.yaml --version 2.0
rdme openapi spec3.yaml --version 2.0
```

The `useSpecVersion` option is there if you want the project version value to be derived from the `info.version` field in your API definition file.

**Comment by cweinberger** [comment]
Ok thanks for explanation! Do you have a suggestion how I can get the spec-version using rdme cli and use it as input for `versions:create` command?

**Comment by kanadgupta** [comment]
@cweinberger when peeking at the work you've done in https://github.com/monta-app/github-workflows/pull/10 (which looks super impressive, by the way!), I'd probably do the following:

1. Use [the `versions` command](https://github.com/readmeio/rdme#get-all-versions-associated-with-your-project) along with [`jq`](https://stedolan.github.io/jq/) to perform some conditional logic to determine whether the version exists in ReadMe or not

2. Grab the spec version value from your spec file using something like [`yq`](https://github.com/kislyuk/yq) or [`jq`](https://stedolan.github.io/jq/) and do something like this:

```yml
- name: Grab ReadMe version
  id: get-version
  run: [some command to grab the version from your file and set it as a step output]

- name: Create version in ReadMe
  uses: readmeio/rdme@v8
  with:
    rdme: versions:create {{ steps.get-version.outputs.version }} --fork={version-you-wish-to-fork-from} --main=false --beta=false --isPublic=false
```

**Comment by kanadgupta** [comment]
Happy to help @cweinberger! A beta release was just tagged if you want to play around with the fix:

https://github.com/readmeio/rdme/releases/tag/8.6.0-next.14
https://www.npmjs.com/package/rdme/v/8.6.0-next.14

You can reference this in your workflows by doing the following:

```yml
- uses: readmeio/rdme@v8.6.0-next.14
  with:
    rdme: openapi
```

Thanks again for writing in about this!
