### ISSUE TITLE
GitHub actions logging sullies `rdme versions` JSON output

### ISSUE THREAD

**Issue by pdconant** [readmeio/rdme#804]
We re trying to use the rdme CLI tool in a script used during our software build process. The script works beautifully when executed locally, but when we run it in GitHub Actions it fails. The problems seems to be that the CLI tool is inserting special GHA-specific logging information into the output when executed in a GHA runtime. For instance, when I run the `rdme versions` command locally, it outputs JSON that I can pipe to another bash tool.  

```
~ rdme versions
[
  {
    "version": "1.0",
    "version_clean": "1.0.0",
    "codename": "",
    "is_stable": true,
    "is_beta": false,
    "is_hidden": false,
    "is_deprecated": false,
    "_id": "64401f72fee0d81a090190a1",
    "createdAt": "2023-04-19T17:05:54.391Z"
  }
]
```

But when I run the same command in a bash script on a GitHub Actions runner, the output is prefixed with GHA-specific logging sytanx:
```
echo '::debug::rdme: raw process.argv: ["versions"]
[
  {
    "version": "1.0",
    "version clean": "1.0.0",
    "codename": "",
    "is_stable": true,
    "is_beta": true,
    "is_hidden": false,
    "is_deprecated": false,
    "_id": "64401f72fee0d81a090190a1",
    "createdAt": "2023-04-1917:05:54.391Z"
  }
]'
```

Is there a way to prevent the rdme CLI from injecting the `::debug::rdme: raw process.argv: ["versions"]` into the output?

**Comment by kanadgupta** [comment]
Hi @pdconant! Could you send across a GitHub Actions workflow file that demonstrates how you're trying to pipe this JSON output into another bash script?

The GitHub Actions runner should be masking those debug statements. We [set the command output as the GitHub job output called `rdme`](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) (i.e., in the case of `rdme versions`, the output is stringified JSON), so I'd use that instead. For example:

```yml
- name: List versions
  uses: readmeio/rdme@v8
  id: rdme-versions
  with:
    rdme: versions

- run: echo ${{ steps.rdme-versions.outputs.rdme }} | jq .
```

Let me know if you have any issues with this technique?

**Comment by pdconant** [comment]
Thanks, Kanad. Our invocation of the `rdme` CLI is part of a larger script that we're would like to use. The relevant bit of the script looks like this: 

```

#
# Find or create the API version at ReadMe
#
VERSION_ID=$(rdme versions | jq -r ".[] | select(.version == \"${VERSION}\") | ._id" )

if [[ -z "${VERSION_ID}" ]] ; then
  if [[ $FILE != *.json ]] ; then
    echo "no VERSION parameter supplied, and cannot extract version from non-JSON API spec."
    exit 2
  fi
  echo 'VERSION does not exist. Creating it...'
  FORK_FROM_VERSION=$(rdme versions | jq -r 'map(select(.is_stable == true)) | map(select(.is_beta == false)) | map(select(.is_deprecated == false)) | sort_by(.createdAt) | reverse | .[0].version')
  if [[ -z "${FORK_FROM_VERSION}" ]] ; then
    echo 'Failed to locate fork-from version!'
    rdme versions
    exit 1
  fi
  if [[ "${BETA}" == 'false' ]]; then
    rdme versions:create "${VERSION}"--fork="${FORK_FROM_VERSION}" --main=false --isPublic=false --beta=false
  else
    rdme versions:create "${VERSION}" --fork="${FORK_FROM_VERSION}" --main=false --isPublic=false --beta=true
    BETA=true
  fi
  VERSION_ID=$(rdme versions | jq -r ".[] | select(.version == \"${VERSION}\") | ._id" )
fi
echo "Publishing version ${VERSION} (${VERSION_ID})."
...
``` 

This works beautifully when executed locally. Extracting each `rdme` CLI invocation from the script and pulling it into a separate GHA step is feasible but terribly inconvenient. It would be strongly preferably to have the CLI output consistent information when invoked in GHA as when invoked outside of GHA. Is there a flag or something I can pass to indicate that the CLI tool should not add GHA-specific logging syntax?

**Comment by pdconant** [comment]
I suppose I can pass the `rdme` output through another tool to strip the unrequested GHA-specific logging stuff out of the output (`rdme versions | sed '/^:/d'`). I will proceed with that approach, but if there's some undocumented CLI flag that'll make the tools operate consistently among runtime environments, I'd prefer that.

**Comment by kanadgupta** [comment]
@pdconant understood, thanks for the context! Unfortunately we don't have any CLI flags to disable this behavior and we recommend using the step outputs instead.

Have you considered parameterizing your `rdme versions` output so you can reuse that as an environment variable in your script? For example, say your workflow file looked like this:

```yml
- name: List versions
  uses: readmeio/rdme@v8
  id: rdme-versions
  with:
    rdme: versions

- run: ./your-script.sh
  env:
    RDME_VERSIONS: ${{ steps.rdme-versions.outputs.rdme }}
```

Then you could reuse that `RDME_VERSIONS` value in your script like so:

```sh
VERSION_ID=$(echo $RDME_VERSIONS | jq -r ".[] | select(.version == \"${VERSION}\") | ._id" )

if [[ -z "${VERSION_ID}" ]] ; then
  if [[ $FILE != *.json ]] ; then
    echo "no VERSION parameter supplied, and cannot extract version from non-JSON API spec."
    exit 2
  fi
  echo 'VERSION does not exist. Creating it...'
  FORK_FROM_VERSION=$(echo $RDME_VERSIONS | jq -r 'map(select(.is_stable == true)) | map(select(.is_beta == false)) | map(select(.is_deprecated == false)) | sort_by(.createdAt) | reverse | .[0].version')
  ...
```

Depending on how your script works, you might need to break it into several steps.

If that isn't a viable option then I'd recommend hitting [the corresponding ReadMe API endpoint](https://docs.readme.com/main/reference/getversions) via `curl` request instead, like so:

```sh
curl https://dash.readme.com/api/v1/version --user rdme_123:
```

**Comment by pdconant** [comment]
Thanks, @kanadgupta -- those are both viable options, but the `sed` filter above was more expedient & seems to have met our immediate need.

**Comment by kanadgupta** [comment]
Sorry these workarounds aren't ideal and glad you figured out a solution @pdconant! Feel free to open up another issue if you need anything else.
