### ISSUE TITLE
Getting "Maximum call stack size exceeded" for validate/inspect commands

### ISSUE THREAD

**Issue by Ebeid** [readmeio/rdme#813]
Getting "Maximum call stack size exceeded" for validate/inspect commands. Using version 8.6.3

**Comment by kanadgupta** [comment]
Hi @Ebeid! Are you seeing this error before or after selecting an API definition? If it's prior to the selection, this is likely a duplicate of #780.

**Comment by Ebeid** [comment]
After
```
rdme openapi:inspect ~/Downloads/swagger.json
✖ Validating the API definition located at /Users/eelsayed/Downloads/swagger.json...

Maximum call stack size exceeded
```

**Comment by kanadgupta** [comment]
Can you send across the file?

**Comment by Ebeid** [comment]
I'm sorry I can't share that json file. The issue seems reproducible with other files that used work before.

**Comment by kanadgupta** [comment]
We need a reproducible example in order to fix the issue. Even a API definition file with redacted or placeholder data would be helpful.

Closing this out but happy to revisit this once we have an example!
