### ISSUE TITLE
"is not a legal HTTP header value" errors when syncing docs

### ISSUE THREAD

**Issue by vegaro** [readmeio/rdme#816]
When calling the `docs` command in GitHub, we hit this error:

```
[21:51:00]: Exit status of command 'rdme docs rendered_docs --version=v5.0 --key=***' was 1 instead of 0.
Error: Error uploading rendered_docs/📈 Dashboard & Metrics/charts/annual-recurring-revenue-arr-chart.md:

[https://github.com/RevenueCat/revenuecat-docs/blob/35ebea8359c25fc4427aa5f965e07c5e29219414/rendered_docs/📈](https://github.com/RevenueCat/revenuecat-docs/blob/35ebea8359c25fc4427aa5f965e07c5e29219414/rendered_docs/%F0%9F%93%88) Dashboard & Metrics/charts/annual-recurring-revenue-arr-chart.md is not a legal HTTP header value
```

Looking at the debug logs, we see headers like these:

```
::debug::rdme: making POST request to https://dash.readme.com/api/v1/docs with headers: {"Authorization":["redacted"],"content-type":["application/json"],"x-readme-version":["5.0"],"User-Agent":["rdme-github/8.6.3"],"x-github-repository":["RevenueCat/revenuecat-docs"],"x-github-run-attempt":["1"],"x-github-run-id":["5149552673"],"x-github-run-number":["12"],"x-github-sha":["redacted"],"x-readme-source-url":["https://github.com/RevenueCat/revenuecat-docs/blob/35ebea8359c25fc4427aa5f965e07c5e29219414/rendered_docs/Transactions - Purchases/defer-a-google-subscription-old.md"],"x-rdme-ci":["GitHub Actions"],"x-readme-source":["cli-gh"]}
```

We suspect it is probably due to the folder name `📈 Dashboard & Metrics` not being encoded correctly when generating the `x-readme-source-url`.

**Comment by kanadgupta** [comment]
Appreciate the debug logs, @vegaro! I was able to reproduce the issue and have a fix up in #817. Will keep you updated on when it's released!

**Comment by kanadgupta** [comment]
Just tagged [v8.6.4-next.2](https://github.com/readmeio/rdme/releases/tag/8.6.4-next.2) — feel free to play around with it and see if it fixes your issue. Will tag a general release on Monday and update this issue once that’s live!

**Comment by vegaro** [comment]
I tested it and it works fine! Thanks for the quick turnaround

**Comment by kanadgupta** [comment]
Hi @vegaro, `v8.6.4` is live in the GitHub and npm registries with this fix:

https://github.com/readmeio/rdme/releases/tag/8.6.4
https://www.npmjs.com/package/rdme/v/8.6.4

If you're using GitHub Actions and you're pointed to `readmeio/rdme@v8`, you should automatically see this fix. Thanks again for writing in about this!
