### ISSUE TITLE
rdme openapi command hangs after Done

### ISSUE THREAD

**Issue by liaz-af** [readmeio/rdme#821]
When VPN to the project Gitlab is open the command `rdme openapi` hangs after this message:`Updating your API docs in ReadMe... done! 🦉`

**Comment by kanadgupta** [comment]
Hi @liaz-af! We'll need more info in order to be helpful here. Can you provide us with debug logs? See [our troubleshooting docs](https://docs.readme.com/main/docs/rdme#troubleshooting) for info on how to do this.

**Comment by liaz-af** [comment]
Thank you @kanadgupta for the link.
The last logs are these:
```
rdme [getGitData] isRepo result: true +37ms
  rdme [getGitData] rawRemotes result: origin
  rdme public
  rdme  +59ms
  rdme [getGitData] remote result: origin +0ms
```

Generally, why are you trying to access my GitLab repo?

**Comment by kanadgupta** [comment]
@liaz-af can you offer more details on the environment that you're running this CLI command in? Are you VPN-ing into a GitLab CI runner or something else?

We run git commands as part of [our CI onboarding workflow](https://docs.readme.com/main/docs/rdme#quick-start), where we recommend a CI workflow based on your git setup. We don't collect any of this data on our end. It currently only supports GitHub Actions but we have plans to support GitLab and other CI providers in the future.

**Comment by kanadgupta** [comment]
@liaz-af bumping this — would appreciate any info you could provide here.

**Comment by kanadgupta** [comment]
Closing this out — feel free to reopen this issue if you're running into problems!
