### ISSUE TITLE
Incorrectly coerces string to datetime

### ISSUE THREAD

**Issue by mt-dfrey** [readmeio/rdme#823]
When I upload an open API spec as below the example value is coerced into a date time

```yml
openapi: 3.1.0
info:
  title: Bug Report
  version: 1.0.0

paths:
  /examlpe:
    get:
      parameters:
        - name: myparameter
          in: query
          schema:
            type: string
            format: date
            example: 2020-11-28
      responses:
        "200":
          description: OK
```

the value `2020-11-28` is coerced into `2020-11-28T00:00:00.000Z`.

the converted json that `rdme` produces in [src/lib/prepareOas.ts](https://github.com/readmeio/rdme/blob/next/src/lib/prepareOas.ts#L200) contains the incorrect coercion:

```json
{
  "openapi": "3.1.0",
  "info": {
    "title": "Bug Report",
    "version": "1.0.0"
  },
  "paths": {
    "/examlpe": {
      "get": {
        "parameters": [
          {
            "name": "myparameter",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date",
              "example": "2020-11-28T00:00:00.000Z"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```

This bug does not occur when the example value is quoted like `example: '2020-11-28'`.

However, in YAML `example: 2020-11-28` the value `2020-11-28` _is a string_.

I tried [the JSON conversion in the OAS spec repo](https://github.com/OAI/OpenAPI-Specification/blob/main/scripts/yaml2json/yaml2json.js) and also [tried with the node `yaml` implementation](https://gist.github.com/mt-dfrey/55d5f2ecbeda8783f628ab04fe19a021) that is compliant with the YAML spec's test suite. Both do not coerce.

This is a bug in rdme's  YAML-to-JSON conversion.

**Comment by kanadgupta** [comment]
Thanks for the detailed investigation, @mt-dfrey! Tagging https://github.com/readmeio/rdme/issues/778 https://github.com/readmeio/oas-normalize/pull/254 for reference

(cc: @erunion)

**Comment by erunion** [comment]
@mt-dfrey What version of `rdme` are you running? I'm unable to replicate this in either this repository or in our [oas-normalize](https://github.com/readmeio/oas-normalize) library that is that `oas.bundle()` call.

### oas-normalize

```js
const OASNormalize = require('oas-normalize').default;

const oas = new OASNormalize('./debug.yml', { colorizeErrors: true, enablePaths: true });

(async () => {
  await oas.load();
  await oas.validate({ convertToLatest: true });
  await oas.bundle().then(definition => {
    console.log(require('util').inspect(definition, false, null, true));
  });
})();
```

![Screen Shot 2023-06-13 at 10 23 50 AM](https://github.com/readmeio/rdme/assets/33762/17195d37-8ae9-4a7a-b51a-031d5cd83455)

### rdme

```diff
diff --git a/src/lib/prepareOas.ts b/src/lib/prepareOas.ts
index 3a34600..3ad338f 100644
--- a/src/lib/prepareOas.ts
+++ b/src/lib/prepareOas.ts
@@ -199,6 +199,8 @@ export default async function prepareOas(
   if (['openapi', 'openapi:inspect', 'openapi:reduce'].includes(command)) {
     api = await oas.bundle();
 
+    console.log(require('util').inspect(api, false, null, true));
+
     debug('spec bundled');
   }
```

![Screen Shot 2023-06-13 at 10 23 50 AM](https://github.com/readmeio/rdme/assets/33762/c6c6241d-ffe9-4f38-821a-396ad4336e6a)

**Comment by mt-dfrey** [comment]
We're on `rdme` version 8.5.0, `oas-normalize` is resolved to 8.3.2 (i should have said that in the original bug report).

I ran the script you shared above in our project and the problem reproduces.

**Comment by mt-dfrey** [comment]
I tried to replicate the same setup in a clean new project. Same node & npm version, same dependencies, same versions for all dependies.
Yet the script & test yml does not reproduce the problem in a new clean setup. But it _does_ reproduce the problem in our existing project.

What am I missing? What else can have side like this?

**Comment by mt-dfrey** [comment]
ok, I found a way to make it work.
Recreating our package lock file and re-installing the newly resolved dependencies fixed the problem.
I'm still not clear why that is... must be some interaction with a version of one of the other transitive dependencies. But who knows which 🤷‍♀️
