### ISSUE TITLE
Sync docs / guides from ReadMe to local

### ISSUE THREAD

**Issue by sblaurock** [readmeio/rdme#825]
I see it's possible to sync docs / guides from a local repository to ReadMe - is it possible to add functionality to sync docs / guides from ReadMe to a local machine? Thank you.

**Comment by kanadgupta** [comment]
Hi @sblaurock — this currently isn't possible via `rdme` but bidirectional syncing is on the horizon (no timeline yet unfortunately). In the meantime, you can pull down docs from ReadMe using [the ReadMe Docs API](https://docs.readme.com/main/reference/getdoc). Hope that helps!

Closing this in favor of #582.
