### ISSUE TITLE
Setting parentDocSlug to '' in the front matter doesn't do anything

### ISSUE THREAD

**Issue by vegaro** [readmeio/rdme#873]
I was having issues removing the parent by setting `parentDocSlug` to `''` in the front matter of the md file. When I set the `parentDoc` to `''` it removed the parent though. 

It looks like the CLI doesn't allow to remove parent docs setting parentDocSlug to `''`?

**Comment by kanadgupta** [comment]
Thanks for reporting — this is likely an issue with the ReadMe API. Will look into this next week!

**Comment by kanadgupta** [comment]
The fix in our API has been approved, will close this when the fix is live in production. Thanks for reporting!

**Comment by kanadgupta** [comment]
Should be fixed now, let me know if you're not seeing the expected behavior. Thanks for reporting!
