### ISSUE TITLE
Github Action not working on self-hosted runners

### ISSUE THREAD

**Issue by Beast12** [readmeio/rdme#909]
Issue: When running the github action readmeio/rdme@v8 on a self-hosted runner, the file can't be found.
Errors:

- Without specifying a file and just let the command find the file(s):
``
Error: We couldn't find an OpenAPI or Swagger definition.
``
- With specifying a file (even through a step for searching the file, and add it to a variable which  points directly to the file)
``
```
YAML_PATH=$(find . -name 'example.yml')
  echo "YAML_PATH=$YAML_PATH" >> $GITHUB_ENV
  echo $YAML_PATH
  shell: /usr/bin/bash -e {0}
./Example-API/example.yml

```
`` Validating the API definition located at ./Example-API/example.yml...
Error: ENOENT: no such file or directory, open './Example-API/example.yml'
`
# Working Action
When running the same commands on the ubuntu-latest (not-self-hosted) everything works as expected:
`
- Validating the API definition located at Example-API/example.yml...
- Staging your API definition for upload...
- Updating your API docs in ReadMe...
✔ Updating your API docs in ReadMe... done! 🦉
You've successfully updated an existing OpenAPI file on your ReadMe project!
`

I also tried this:
https://github.com/readmeio/rdme#override-the-working-directory
Same result

**Comment by kanadgupta** [comment]
Hi @Beast12! Unfortunately it's difficult for us to troubleshoot issues with self-hosted runners. If it's working as expected on `ubuntu-latest`, it's likely an issue with your runner setup. Is the repository public? If not, could you provide some more information:
- The architecture / operating system of your runner
- The full GitHub Actions workflow file where you're invoking `rdme`

I'd recommend using a tool like [`mxschmitt/action-tmate`](https://github.com/mxschmitt/action-tmate) for understanding your runner's file system. It's very possible that the repository isn't being checked out properly.

**Comment by kanadgupta** [comment]
Going to close this out since we haven't heard from you, but feel free to drop a note if you have any more questions. Thanks!
