### ISSUE TITLE
ApiDefinitions and Guides marked as hidden

### ISSUE THREAD

**Issue by gustavo-m-vieira** [readmeio/rdme#910]
I am integrating with Readme and I have some doubts about mark pages as hidden. When using the console, I can define that some guide or api definition as hidden, but when I see the CLI and API's documentation there isn't an option to define this.
I see that I can define a version as hidden, but theres is a way that, through CLI or API call define a guide or a apiDefinition as such?

**Comment by kanadgupta** [comment]
Hi @gustavo-m-vieira! For each Guides/Reference page you want to hide, you can set `hidden: true` in the YAML front matter for its corresponding Markdown page. You can read more about this in our docs: https://docs.readme.com/main/docs/rdme#/specifying-other-attributes
