### ISSUE TITLE
match ids to changed files for syncing in github actions

### ISSUE THREAD

**Issue by jebertz** [readmeio/rdme#911]
This is probably more of a question.  So we have our endpoints set up as different OAS files by resource, and I want to do something like: 
```
  - name: Rdme sync for every changed file
    if: ${{ steps.changed-oas-files.outputs.any_changed == 'true' }}
    shell: bash
    run: |
      for file in ${{ steps.changed-oas-files.outputs.all_changed_files }}; do
        npx rdme openapi $(echo "$file" | cut -d/ -f3) --workingDirectory=external-v3/webadmin --version=v3 --key=${{ secrets.README_API_KEY }}
      done
```
The problem I'm running into is that I can't use --update because we have 10 resources (and counting), but I'm not sure of a good way to specify an id per file, especially in a way that I can pull it from github actions?  Do you have any suggestions or am I missing something?

**Comment by kanadgupta** [comment]
Hey @jebertz! Without having much context into your workflow logic, I'd probably do something along these lines:

- Create some sort of mapping between the files and their ReadMe API definition IDs. [Check out these docs](https://docs.readme.com/main/docs/github-actions-openapi-example#/constructing-a-github-actions-workflow-file-by-hand:~:text=uploading%20a%20file%20directly%20into%20the%20ReadMe%20dashboard) for info on obtaining the API definition IDs.
- Enhance the logic of the `changed-oas-files` step to include an output variable that allows the `rdme` command to access the API definition ID for each respective changed file
- Update your `rdme` command to look something like this[^1]:

```diff
- npx rdme openapi $(echo "$file" | cut -d/ -f3) --workingDirectory=external-v3/webadmin --version=v3 --key=${{ secrets.README_API_KEY }}
+ npx rdme openapi $(echo "$file" | cut -d/ -f3) --workingDirectory=external-v3/webadmin --id=$api_definition_id --key=${{ secrets.README_API_KEY }}
```

Hope that's helpful!

I also want to acknowledge that the whole API definition ID paradigm is ripe for improvement and we are in the process of thinking through bigger breaking changes to our API that should make this easier. We'll provide updates as we have them in #473!

[^1]: And yes — by passing the `id` flag, you no longer need to include the `version` flag.

**Comment by jebertz** [comment]
Actually, do you have any examples or suggestions on how to pull IDs from a config file?  Right now we're using an external tool to get the changed files.  If it's helpful, our entire pipeline is `name: ReadMe sync

on:
  pull_request:
    branches:
      - main

jobs:
  rdme-openapi-sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed oas files
        id: changed-oas-files
        uses: tj-actions/changed-files@v39
        with:
          files: external-v3/webadmin*

      - name: print changed oas files
        run: echo "OAS changes to ${{ steps.changed-oas-files.outputs.all_changed_files }}"

      - name: Get changed markdown files
        id: changed-md-files
        uses: tj-actions/changed-files@v39
        with:
          files: external-v3/docs/*

      - name: print changed md files
        run: echo "MD changes to ${{ steps.changed-md-files.outputs.all_changed_files }}"

      - name: Install dependencies
        if: ${{ steps.changed-oas-files.outputs.any_changed == 'true' || steps.changed-md-files.outputs.any_changed == 'true' }}
        uses: ./.github/workflows/actions/install-dependencies

      - name: Rdme sync for every changed file
        if: ${{ steps.changed-oas-files.outputs.any_changed == 'true' }}
        shell: bash
        run: |
          for file in ${{ steps.changed-oas-files.outputs.all_changed_files }}; do
            npx rdme openapi $(echo "$file" | cut -d/ -f3) --workingDirectory=external-v3/webadmin --version=v3 --key=${{ secrets.README_API_KEY }}
          done

      - name: Rdme sync for every changed markdown file
        if: ${{ steps.changed-md-files.outputs.any_changed == 'true' }}
        shell: bash
        run: |
          for file in ${{ steps.changed-md-files.outputs.all_changed_files }}; do
            npx rdme docs $(echo "external-v3/docs/$file" | cut -d/ -f3) --version=v3 --key=${{ secrets.README_API_KEY }}
          done`

**Comment by kanadgupta** [comment]
Hey @jebertz — here's a suggested bash approach!

```sh
files=(petstore.json openapi-test.json this-throws-an-error)
for file in "${files[@]}"; do
    case "$file" in
        # here is where you would map your file names to API definition IDs
        petstore.json) definition_id="651c...";;
        openapi-test.json) definition_id="761de...";;
        *) printf "error: no hash for file %s\n" "$file"; exit 1;;
    esac

    npx rdme openapi $(echo "$file" | cut -d/ -f3) --workingDirectory=external-v3/webadmin --id="$definition_id" --key=${{ secrets.README_API_KEY }}
done
```

I'd also suggest moving that bash script to its own separate file and running the file via the GitHub Action step, like so:

```
- name: Rdme sync for every changed file
  run: sync-oas-to-readme.sh
  env:
    FILES: ${{ steps.changed-oas-files.outputs.all_changed_files }}
```

That way it'll be a bit easier to test and run [shellcheck](https://www.shellcheck.net/) on, which should result in safer bash code!

**Comment by jebertz** [comment]
We got that working, thank you!
