### ISSUE TITLE
Unknown error (Invalid character in header content ["Location"])

### ISSUE THREAD

**Issue by hyungjun7** [readmeio/rdme#923]
The request to POST https://dash.readme.com/api/v1/api-registry returned a status code of 201, but the subsequent PUT request I received this error. How should we solve it? 

rdme openapi temp-api.yaml --key=${{ env.API_KEY }} --id=${{ env.API_ID }}

received status code 400 from [https://dash.readme.com/api/v1/api-specification/](https://dash.readme.com/api/v1/api-specification/xxx) {"error":"INTERNAL_ERROR","message":"Unknown error (Invalid character in header content [\"Location\"]).","suggestion":"Sorry this error isn't more helpful… if you're seeing this, we're stumped too! But email support (support@readme.io) and we can figure it out with you."

**Comment by kanadgupta** [comment]
Hi! Can you get in touch with us at support@readme.io? This likely is a URL encoding issue that's specific to your project.
