### ISSUE TITLE
Suggestion: also support `README_API_KEY` in addition to `RDME_API_KEY`

### ISSUE THREAD

**Issue by nickcampbell18** [readmeio/rdme#948]
Hi folks 👋 

We recently switched from using the GitHub action to a shell script, because we wanted some extra automation around the deployment. Locally we use `rdme login`, but in CI we just use an API key.

Anyway, I exported the environment variable `README_API_KEY` based on the secret we'd set for the action - `${{ secrets.README_API_KEY }}` - but my command failed telling me I needed a `--key` argument. It was only after re-reading the docs I noticed the subtle difference and I should have used `RDME_...`!

Do you think it might be worth also checking for `README_API_KEY` in addition to the existing one? Seems unlikely I would be using `README_API_KEY` to do something else, so this could be a neat ergonomics improvement IMO.

**Comment by serverlessmike** [comment]
Z

**Comment by kanadgupta** [comment]
@nickcampbell18 this change was added in `9.0.0-next.8`. Thanks for writing in about this!

https://github.com/readmeio/rdme/releases/tag/9.0.0-next.8
https://www.npmjs.com/package/rdme/v/9.0.0-next.8
