### ISSUE TITLE
[Question] How to create categories from OpenAPI

### ISSUE THREAD

**Issue by ManuLpz4** [readmeio/rdme#991]
Hi guys! Hope you are doing well :)

Do you know if there is any way to create categories instead of pages from an OpenAPI spec?

Please and thank you so much

**Comment by kanadgupta** [comment]
Hi @ManuLpz4! Right now, when you upload a new OpenAPI file to ReadMe, we automatically create a new category, as well as all of the pages — this is based on how you define your tags and endpoints in your OpenAPI definition. You can read more about this in our docs: https://docs.readme.com/main/docs/openapi-categories-pages-subpages

Hope that answers your question. Thanks!

**Comment by kanadgupta** [comment]
Hi there, we haven't heard from you so I'm going to close this out. Let us know if you have any other questions!
